server {
    listen 8080;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location = /report.sarif {
        dav_methods DELETE;
        limit_except GET HEAD DELETE { deny all; }
    }

    location = /scan-meta.json {
        dav_methods DELETE;
        limit_except GET HEAD DELETE { deny all; }
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
